/*
 SCRIPT FOR CREATING CLIENT TABLE
*/

CREATE TABLE CLIENT (
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	NAME VARCHAR(150) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	BIRTHDATE DATE NOT NULL
);

-- INSERT ONE RECORD INTO CLIENT TABLE

INSERT INTO CLIENT (ID, NAME, EMAIL, BIRTHDATE)
VALUES 
(NEWID(), 'Mary Poppins', 'marypoppins@gmail.com', '2000-01-10'),
(NEWID(), 'Paul Richard', 'paulrichard@gmail.com', '1988-10-02')

-- CONSULTING THE CLIENT TABLE
SELECT * FROM CLIENT
ORDER BY NAME;